name: lingo
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest ,ubuntu-latest]
        cxx-version: [11, 14, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: "source"
      - run: mkdir build
      - name: Configure
        working-directory: ./build
        run: cmake -D LINGO_TEST_CXX_VERSION=${{ matrix.cxx-version }} ../source
      - name: Build
        working-directory: ./build
        run: cmake --build .
      - name: Test
        working-directory: ./build
        run: ctest
