name: lingo
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest ,ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: "source"
      - run: mkdir build
      - name: Configure
        working-directory: ./build
        run: cmake ../source
      - name: Build
        working-directory: ./build
        run: cmake --build .
      - name: Test
        working-directory: ./build
        run: ctest
