name: main
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Create
        run: |
          mkdir build
          cd build
      - name: Configure
        run: cmake ..
      - name: Build
        run: cmake --build .
      - name: Test
        run: ctest
      